[robot]
hardware = "R1_LITE"

# comment out keys you don't want to publish
enable_publish = [
    #"left_arm",
    #"left_gripper",
    #"left_ee_pose",
    "right_arm",
    "right_gripper",
    #"right_ee_pose",
    "torso",
    #"chassis",
]

[basic]
use_ehi = false
control_frequency = 15.0
step_mode = "sync"
action_steps = 32

[model]
ckpt_dir = "/replace/with/your/model/path"
processor = "default"
use_trt = false
is_torch_compile = false

[trajectory]
ensemble_mode = "HATO"
execution_mode = "JOINT_STATE"

[websocket]
use_websocket = false
host = "0.0.0.0"
port = 8080

[instruction]
use_vlm = false
bbox_as_instruction = false
image_condition_lang_prefix = false
pp_lower_half = false
image_as_condition = false

[visualization]
enabled = true
output_dir = ""
render_every_n_publishes = 5
keep_chunks = 12
keep_publish_events = 400
